sudo: false
language: python
python:
    - "3.7"
install:
    - pip install tox-travis
    - pip install coverage
before_script: cd webroot
script:
    - tox
    - coverage run
    - coverage report --include="*webroot*" --omit="*test*"